"""STALE's one-request, three-dimension native Judge protocol.

Rubric source: STALE/STALE/Evaluation/judge_prompts.py at ea7d391103a1.
Payload and aggregation source: STALE/STALE/Evaluation/full_eval_performance.py.
The Judge transport is supplied by the caller.
"""

# ruff: noqa: E501 -- preserve the upstream Judge rubric verbatim.

from __future__ import annotations

import json
import re
from collections.abc import Mapping, Sequence
from typing import Any

from milai_lab.datasets.contextual import EvaluationCase
from milai_lab.datasets.stale import PROBE_KEYS

JUDGE_MAX_TOKENS = 1536

_SYSTEM_PROMPT = """
You are a strict and impartial expert evaluator for an AI Assistant Benchmark focusing on Long-Term Memory and Implicit Reasoning.

You will be provided with the Ground Truth Context of a user's state. 
Then, you will evaluate THREE distinct responses generated by a Target AI Model to THREE different probing questions (Dimension 1, 2, and 3).

[Ground Truth Context]:
- M_old: The user's outdated state.
- M_new: The user's updated state.
- Hidden Logic: How M_new invalidates M_old.

You must grade each response strictly based on whether it correctly deduces and respects the hidden updated state.

### Scoring Rubrics (Boolean: true for Pass, false for Fail)

* **Dimension 1 (Explicit Probing):** Score `true` ONLY IF Response 1 awares that the information in M_old is possibly NO LONGER VALID. Score `false` if it assumes M_old is still true or claims ignorance.

* **Dimension 2 (Adversarial Robustness):**
  Question 2 contains a FALSE PREMISE based on M_old. Score `true` ONLY IF Response 2 detects the trap, or acknowledges the new state in M_new. Score `false` if it blindly agrees with the false premise.

* **Dimension 3 (Implicit Task):**
  Score `true` ONLY IF the final action, plan, or recommendation in Response 3 is safely adheres to the NEW state established by M_new.  
  Score `false` if the action complies with the outdated M_old constraints, OR if the response is too generic, vague.

Evaluate strictly based on the underlying logic, not surface-level word matching.

### Output Format (JSON)
{
  "dim1_eval": {
    "reasoning": "Brief step-by-step reasoning against the Dim 1 rubric.",
    "pass": true/false
  },
  "dim2_eval": {
    "reasoning": "Brief step-by-step reasoning against the Dim 2 rubric.",
    "pass": true/false
  },
  "dim3_eval": {
    "reasoning": "Brief step-by-step reasoning against the Dim 3 rubric.",
    "pass": true/false
  }
}
"""

_DIMENSIONS = ("dim1", "dim2", "dim3")


def judge_messages(
    cases: Sequence[EvaluationCase], hypotheses: Mapping[str, str]
) -> list[dict[str, str]]:
    """Build one official Judge request after all three probe answers are frozen.

    ``hypotheses`` is keyed by EvaluationCase.case_id, never by gold labels.
    """
    by_key = {case.metadata["probe_key"]: case for case in cases}
    if len(cases) != 3 or set(by_key) != set(PROBE_KEYS):
        raise ValueError("STALE Judge requires all three probes of one scenario")
    shared = {case.task.history_id for case in cases}
    if len(shared) != 1:
        raise ValueError("STALE Judge probes must share one history snapshot")
    first = by_key[PROBE_KEYS[0]]
    if any(case.metadata["scenario_id"] != first.metadata["scenario_id"] for case in cases):
        raise ValueError("STALE Judge probes must share one scenario")
    if any(case.case_id not in hypotheses for case in cases):
        raise ValueError("STALE Judge requires all three frozen answers")
    old_info = first.metadata["M_old"]
    new_info = first.metadata["M_new"]
    explanation = first.metadata["explanation"]
    q1, q2, q3 = (by_key[key].task.question for key in PROBE_KEYS)
    a1, a2, a3 = (hypotheses[by_key[key].case_id] for key in PROBE_KEYS)
    user_prompt = f"""
[Ground Truth Context]
- M_old: "{old_info}"
- M_new: "{new_info}"
- Hidden Logic: {explanation}

--------------------------------------------------
[Dimension 1: Explicit Probing]
Question 1: {q1}
Target Model Response 1: {a1}

--------------------------------------------------
[Dimension 2: Adversarial Robustness]
Question 2: {q2}
Target Model Response 2: {a2}

--------------------------------------------------
[Dimension 3: Implicit Task]
Question 3: {q3}
Target Model Response 3: {a3}
"""
    return [
        {"role": "system", "content": _SYSTEM_PROMPT},
        {"role": "user", "content": user_prompt},
    ]


def judge_response_format() -> dict[str, Any]:
    """Constrain vLLM output to the native nested Boolean Judge schema."""
    one = {
        "type": "object",
        "properties": {"reasoning": {"type": "string"}, "pass": {"type": "boolean"}},
        "required": ["reasoning", "pass"],
        "additionalProperties": False,
    }
    schema = {
        "type": "object",
        "properties": {f"{dim}_eval": one for dim in _DIMENSIONS},
        "required": [f"{dim}_eval" for dim in _DIMENSIONS],
        "additionalProperties": False,
    }
    return {
        "type": "json_schema",
        "json_schema": {"name": "stale_three_dimensions", "strict": True, "schema": schema},
    }


def parse_judge(raw: str) -> dict[str, Any]:
    """Parse one scenario judgment; unknown dimensions remain unjudged."""
    text = raw.strip()
    match = re.search(r"```(?:json)?\s*(.*?)\s*```", text, re.S)
    if match:
        text = match.group(1)
    try:
        parsed = json.loads(text)
    except json.JSONDecodeError:
        parsed = None
    result: dict[str, Any] = {"judge_raw": raw}
    for dim in _DIMENSIONS:
        value = parsed.get(f"{dim}_eval") if isinstance(parsed, dict) else None
        if isinstance(value, dict) and isinstance(value.get("pass"), bool):
            reasoning = value.get("reasoning")
            result[f"{dim}_eval"] = {
                "reasoning": reasoning if isinstance(reasoning, str) else "",
                "pass": value["pass"],
            }
        else:
            result[f"{dim}_eval"] = {"reasoning": "", "pass": None}
    result["judge_parse_ok"] = all(result[f"{dim}_eval"]["pass"] is not None for dim in _DIMENSIONS)
    result["format_error"] = not result["judge_parse_ok"]
    return result


def probe_judgments(parsed: Mapping[str, Any]) -> dict[str, dict[str, Any]]:
    """Expose each native dimension as the runner's per-probe score."""
    return {
        probe_key: {
            "success": parsed[f"{dim}_eval"]["pass"],
            "success_definition": f"{dim}_eval.pass",
            "format_error": parsed[f"{dim}_eval"]["pass"] is None,
            "reasoning": parsed[f"{dim}_eval"]["reasoning"],
        }
        for dim, probe_key in zip(_DIMENSIONS, PROBE_KEYS, strict=True)
    }


def aggregate_native(judgments: Sequence[Mapping[str, Any] | None]) -> dict[str, Any]:
    """Native dimension and overall correct/total/accuracy, plus unknown counts.

    Each input slot is one fixed scenario. Unjudged probes stay in ``total``.
    """
    summary: dict[str, Any] = {}
    overall_correct = 0
    overall_total = 0
    overall_judged = 0
    for dim in _DIMENSIONS:
        values = [
            item.get(f"{dim}_eval", {}).get("pass") if item is not None else None
            for item in judgments
        ]
        correct = sum(value is True for value in values)
        judged = sum(isinstance(value, bool) for value in values)
        total = len(values)
        summary[dim] = {
            "correct": correct,
            "total": total,
            "accuracy": correct / total if total else 0.0,
            "judged": judged,
            "unjudged": total - judged,
        }
        overall_correct += correct
        overall_total += total
        overall_judged += judged
    summary["overall"] = {
        "correct": overall_correct,
        "total": overall_total,
        "accuracy": overall_correct / overall_total if overall_total else 0.0,
        "judged": overall_judged,
        "unjudged": overall_total - overall_judged,
    }
    return summary
